const API=window.API_BASE.replace(/\/$/,"");let token=localStorage.getItem("amadeus_token"),stream,coords=null;
const $=x=>document.getElementById(x);const show=m=>$("msg").textContent=m;
function toggle(reg){$("login").hidden=reg;$("register").hidden=!reg}
async function api(path,opt={}){opt.headers={"Content-Type":"application/json",...(opt.headers||{})};if(token)opt.headers.Authorization="Bearer "+token;const r=await fetch(API+path,opt);const d=await r.json();if(!r.ok)throw Error(d.error||"Request gagal");return d}
async function login(){try{const d=await api("/api/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("password").value})});token=d.token;localStorage.amadeus_token=token;start()}catch(e){show(e.message)}}
async function register(){try{const d=await api("/api/register",{method:"POST",body:JSON.stringify({name:$("name").value,email:$("re").value,password:$("rp").value})});token=d.token;localStorage.amadeus_token=token;start()}catch(e){show(e.message)}}
function logout(){localStorage.removeItem("amadeus_token");location.reload()}
async function start(){try{const u=await api("/api/me");$("auth").hidden=true;$("panel").hidden=false;$("welcome").textContent="Halo, "+u.name;openCamera();getGPS();loadHistory()}catch(e){logout()}}
async function openCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:720}},audio:false});$("video").srcObject=stream}catch(e){show("Kamera tidak tersedia. Beri izin kamera dan gunakan HTTPS.")}}
function getGPS(){if(!navigator.geolocation)return $("location").textContent="GPS tidak tersedia";navigator.geolocation.getCurrentPosition(p=>{coords={lat:p.coords.latitude,lng:p.coords.longitude};$("location").textContent=`GPS aktif • ${coords.lat.toFixed(5)}, ${coords.lng.toFixed(5)}`},e=>$("location").textContent="Izin GPS ditolak",{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
async function submitAttendance(type){if(!coords)return show("Tunggu sampai GPS aktif.");const v=$("video"),c=$("canvas");if(!v.videoWidth)return show("Kamera belum siap.");c.width=v.videoWidth;c.height=v.videoHeight;c.getContext("2d").drawImage(v,0,0);const photo=c.toDataURL("image/jpeg",.75);try{await api("/api/attendance",{method:"POST",body:JSON.stringify({type,photo,lat:coords.lat,lng:coords.lng,client_time:new Date().toISOString()})});show("Absensi berhasil tersimpan.");loadHistory()}catch(e){show(e.message)}}
async function loadHistory(){try{const rows=await api("/api/my-attendance");$("history").innerHTML=rows.map(r=>`<div class="row"><b>${r.type==="in"?"Masuk":"Pulang"}</b> — ${new Date(r.server_time).toLocaleString("id-ID")}<br><small>${r.status} • ${Math.round(r.distance_m)} m dari titik kantor</small></div>`).join("")||"<p>Belum ada absensi.</p>"}catch(e){}}
if(token)start();